appParameters:
  enableOperatorChaining: "false"
  input-minNumSegments: 1
  input-startAtTail: "true"
  input-stream: multi-video-grid-output
  maxOutOfOrdernessMs: 1000
flinkVersion: 1.9.1
imageRef:
  name: 1.9.1-2.12
mainClass: io.pravega.example.videoprocessor.VideoReaderJob
mavenCoordinate:
  artifact: flinkprocessor
  group: io.pravega.example.video
  version: 0.1.0
parallelism: 1
taskManager:
  cpu: 250m
  memory: 1G
  heap: 512m
  replicas: 1
  taskSlots: 1
