VideoDataGeneratorJob:
  parallelism: 4
  enableOperatorChaining: "true"
  numCameras: 4
  imageWidth: 367
  chunkSizeBytes: 524288
  framesPerSec: 3.0
  taskManager:
    replicas: 4
    memory: 2G
    cpu: 500m
    taskSlots: 1

MultiVideoGridJob:
  enabled: true
  parallelism: 4
  readerParallelism: 1
  enableOperatorChaining: "true"
  framesPerSec: 1.0
  maxOutOfOrdernessMs: 1000
  checkpointIntervalMs: 15000
  input:
    stream: video2
    minNumSegments: 1
  output:
    stream: grid1
    minNumSegments: 1
  taskManager:
    replicas: 4
    memory: 2G
    cpu: 1000m
    taskSlots: 1

VideoReaderJob:
  enabled: true
