mavenCoordinate:
  group: io.pravega.example.video
  artifact: flinkprocessor
  version: 0.1.0


FlinkObjectDetectorJob:
  scope: "object-detection"
  enabled: true
  parallelism: 1
  enableOperatorChaining: "false"
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 2
    memory: 50G
    cpu: 3072m
    taskSlots: 5

