mavenCoordinate:
  group: io.pravega.example.video
  artifact: flinkprocessor
  version: 0.1.0

FlinkObjectDetectorJob:
  scope: "examples"
  enabled: true
  parallelism: 1
  enableOperatorChaining: "false"
  input:
    stream: video1
    minNumSegments: 1
  output:
    stream: examples-detected
    minNumSegments: 1
  startAtTail: "true"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 20G
    cpu: 5000m
    heap: 500m
    taskSlots: 5

VideoDataGeneratorJob:
  enabled: true
  parallelism: 1
  enableOperatorChaining: "false"
  useCachedFrame: "false"
  numCameras: 1
  imageWidth: 100
  framesPerSec: 1.0
  chunkSizeBytes: 524288
  taskManager:
    replicas: 1
    memory: 2G
    cpu: 250m
    taskSlots: 2

MultiVideoGridJob:
  enabled: false
  parallelism: 1
  readerParallelism: -1
  enableOperatorChaining: "false"
  input:
    stream: video1
    minNumSegments: 1
  output:
    stream: grid1
    minNumSegments: 1
  imageWidth: 75
  framesPerSec: 1.0
  chunkSizeBytes: 524288
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  checkpointIntervalMs: 300000
  taskManager:
    replicas: 1
    memory: 8G
    cpu: 1000m
    taskSlots: 4

VideoReaderJob:
  enabled: false
  parallelism: 1
  enableOperatorChaining: "false"
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 4G
    cpu: 250m
    taskSlots: 1


