apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: ClusterFlinkImage
metadata:
  name: cuda10.0flink1.7.2
spec:
  apiversion: v1
  docker:
    image:  pvthejas/flinkcuda:cuda10.0flink1.7.2
    pullPolicy: Always
  flinkVersion: 1.7.2
