apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: ClusterFlinkImage
metadata:
  name: cuda10.0flink1.7.2
spec:
  apiversion: v1
  docker:
    image:  RegistryName/cuda10.0flink1.7.2            # Specify your CUDAFlink Image reference here with appropriate registry name
    pullPolicy: Always
  flinkVersion: 1.7.2
