apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: videodemo2
  region: us-east-1
nodeGroups:
  - name: standard-workers
    availabilityZones: ["us-east-1b"]
    instanceType: p3.2xlarge
    desiredCapacity: 5
    ssh:
      publicKeyName: "faheyc@ubuntu"
