hub:
  extraConfig:
    # Below changed per https://github.com/jupyter/docker-stacks/issues/1041.
    jupyterlab: |
      c.Spawner.default_url = "/lab"

prePuller:
  hook:
    enabled: false

singleuser:
  cpu:
    limit: 2.0
    guarantee: 0.5
  defaultUrl: "/lab"
  extraEnv:
    pravega_client_auth_method: "Bearer"
    pravega_client_auth_loadDynamic: "true"
    PRAVEGA_GRPC_GATEWAY_ADDRESS: "pravega-grpc-gateway:80"
    KEYCLOAK_SERVICE_ACCOUNT_FILE: "/var/run/secrets/nautilus.dellemc.com/serviceaccount/keycloak.json"
  image:
    name: jupyter/minimal-notebook
    tag: ae5f7e104dd5
  imagePullPolicy: Always
  memory:
    limit: 2G
    guarantee: 1G
  profileList:

    - display_name: "Jupyter TensorFlow Notebook 2020-03-17"
      default: true
      kubespawner_override:
        image: jupyter/tensorflow-notebook:dc9744740e12

    - display_name: "Jupyter All Spark Notebook 2020-03-17"
      default: false
      kubespawner_override:
        image: jupyter/all-spark-notebook:dc9744740e12

    - display_name: "Jupyter All Spark Notebook 2019-04-22"
      default: false
      kubespawner_override:
        image: jupyter/all-spark-notebook:f646d2b2a3af

  storage:
    extraVolumes:
      - name: examples-pravega
        secret:
          secretName: examples-pravega
      - name: data-project
        persistentVolumeClaim:
          claimName: data-project
    extraVolumeMounts:
      - name: examples-pravega
        mountPath: /var/run/secrets/nautilus.dellemc.com/serviceaccount
      - name: data-project
        mountPath: /home/jovyan/data-project

proxy:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "jupyterhub.examples.frightful-four.eaglemonk.intranet.nautilus-platform-dev.com"
      #external-dns.alpha.kubernetes.io/hostname: "jupyterhub.examples.microbe.eaglemonk.intranet.nautilus-platform-dev.com"
